export const products = [
  {
    id: 1,
    name: "iPhone 16 Pro Max",
    brand: "Apple",
    price: 189990,
    year: "2025",
    screen_size: "6.9″",
    ram: "8 ГБ",
    storage: "1 ТБ",
    screen_type: "LTPO",
    refresh_rate: "120 Гц",
    camera_mp: "200 МП+",
    battery: "5000–6000 мАч",
    waterproof: "IP68",
    color: "Титановый",
    availability: "В наличии",
    rating: "4.8"
  },
  {
    id: 2,
    name: "Samsung Galaxy S25 Ultra",
    brand: "Samsung",
    price: 159990,
    year: "2025",
    screen_size: "6.8″",
    ram: "16 ГБ",
    storage: "512 ГБ",
    screen_type: "AMOLED",
    refresh_rate: "144+ Гц",
    camera_mp: "200 МП+",
    battery: "5000–6000 мАч",
    waterproof: "IP68",
    color: "Чёрный",
    availability: "В наличии",
    rating: "4.7"
  },
  {
    id: 3,
    name: "Xiaomi 15 Pro",
    brand: "Xiaomi",
    price: 89990,
    year: "2025",
    screen_size: "6.7″",
    ram: "16 ГБ",
    storage: "1 ТБ",
    screen_type: "AMOLED",
    refresh_rate: "120 Гц",
    camera_mp: "108 МП",
    battery: "6000+ мАч",
    waterproof: "IP68",
    color: "Зелёный",
    availability: "В наличии",
    rating: "4.6"
  },
  {
    id: 4,
    name: "Google Pixel 9 Pro XL",
    brand: "Google",
    price: 134990,
    year: "2025",
    screen_size: "6.8″",
    ram: "16 ГБ",
    storage: "512 ГБ",
    screen_type: "OLED",
    refresh_rate: "120 Гц",
    camera_mp: "50–64 МП",
    battery: "5000–6000 мАч",
    waterproof: "IP68",
    color: "Белый",
    availability: "В наличии",
    rating: "4.9"
  },
  {
    id: 5,
    name: "Samsung Galaxy S24 FE",
    brand: "Samsung",
    price: 54990,
    year: "2024",
    screen_size: "6.7″",
    ram: "8 ГБ",
    storage: "256 ГБ",
    screen_type: "AMOLED",
    refresh_rate: "120 Гц",
    camera_mp: "50–64 МП",
    battery: "4500–5000 мАч",
    waterproof: "IP68",
    color: "Синий",
    availability: "В наличии",
    rating: "4.5"
  },
  {
    id: 6,
    name: "iPhone 15 Pro",
    brand: "Apple",
    price: 119990,
    year: "2023",
    screen_size: "6.1″",
    ram: "8 ГБ",
    storage: "512 ГБ",
    screen_type: "LTPO",
    refresh_rate: "120 Гц",
    camera_mp: "48 МП",
    battery: "До 4500 мАч",
    waterproof: "IP68",
    color: "Титановый",
    availability: "Под заказ",
    rating: "4.7"
  },
  {
    id: 7,
    name: "Realme GT 7 Pro",
    brand: "Realme",
    price: 59990,
    year: "2025",
    screen_size: "6.8″",
    ram: "12 ГБ",
    storage: "512 ГБ",
    screen_type: "AMOLED",
    refresh_rate: "144+ Гц",
    camera_mp: "108 МП",
    battery: "6000+ мАч",
    waterproof: "IP68",
    color: "Зелёный",
    availability: "В наличии",
    rating: "4.6"
  },
  {
    id: 8,
    name: "Xiaomi 14T Pro",
    brand: "Xiaomi",
    price: 72990,
    year: "2024",
    screen_size: "6.67″",
    ram: "12 ГБ",
    storage: "512 ГБ",
    screen_type: "AMOLED",
    refresh_rate: "144+ Гц",
    camera_mp: "50–64 МП",
    battery: "5000–6000 мАч",
    waterproof: "IP68",
    color: "Чёрный",
    availability: "В наличии",
    rating: "4.5"
  },
  {
    id: 9,
    name: "Huawei Pura 70 Ultra",
    brand: "Huawei",
    price: 109990,
    year: "2024",
    screen_size: "6.8″",
    ram: "16 ГБ",
    storage: "1 ТБ",
    screen_type: "OLED",
    refresh_rate: "120 Гц",
    camera_mp: "200 МП+",
    battery: "5000–6000 мАч",
    waterproof: "IP68",
    color: "Зелёный",
    availability: "Под заказ",
    rating: "4.8"
  },
  {
    id: 10,
    name: "Oppo Find X8 Pro",
    brand: "Oppo",
    price: 94990,
    year: "2025",
    screen_size: "6.78″",
    ram: "16 ГБ",
    storage: "512 ГБ",
    screen_type: "AMOLED",
    refresh_rate: "120 Гц",
    camera_mp: "108 МП",
    battery: "5000–6000 мАч",
    waterproof: "IP68",
    color: "Фиолетовый",
    availability: "В наличии",
    rating: "4.7"
  },
  {
    id: 11,
    name: "Vivo X200 Pro",
    brand: "Vivo",
    price: 89990,
    year: "2025",
    screen_size: "6.78″",
    ram: "16 ГБ",
    storage: "1 ТБ",
    screen_type: "AMOLED",
    refresh_rate: "120 Гц",
    camera_mp: "200 МП+",
    battery: "6000+ мАч",
    waterproof: "IP68",
    color: "Белый",
    availability: "В наличии",
    rating: "4.8"
  },
  {
    id: 12,
    name: "Sony Xperia 1 VII",
    brand: "Sony",
    price: 139990,
    year: "2025",
    screen_size: "6.5″",
    ram: "12 ГБ",
    storage: "512 ГБ",
    screen_type: "OLED",
    refresh_rate: "120 Гц",
    camera_mp: "50–64 МП",
    battery: "До 4500 мАч",
    waterproof: "IP68",
    color: "Чёрный",
    availability: "Под заказ",
    rating: "4.6"
  },
  {
    id: 13,
    name: "Redmi Note 14 Pro+",
    brand: "Xiaomi",
    price: 34990,
    year: "2025",
    screen_size: "6.67″",
    ram: "12 ГБ",
    storage: "512 ГБ",
    screen_type: "AMOLED",
    refresh_rate: "120 Гц",
    camera_mp: "50–64 МП",
    battery: "6000+ мАч",
    waterproof: "IP68",
    color: "Синий",
    availability: "В наличии",
    rating: "4.4"
  },
  {
    id: 14,
    name: "Samsung Galaxy A56",
    brand: "Samsung",
    price: 42990,
    year: "2025",
    screen_size: "6.7″",
    ram: "8 ГБ",
    storage: "256 ГБ",
    screen_type: "AMOLED",
    refresh_rate: "120 Гц",
    camera_mp: "До 48 МП",
    battery: "5000–6000 мАч",
    waterproof: "IP67",
    color: "Зелёный",
    availability: "В наличии",
    rating: "4.5"
  },
  {
    id: 15,
    name: "iPhone 16",
    brand: "Apple",
    price: 99990,
    year: "2025",
    screen_size: "6.1″",
    ram: "8 ГБ",
    storage: "256 ГБ",
    screen_type: "OLED",
    refresh_rate: "60 Гц",
    camera_mp: "48 МП",
    battery: "До 4500 мАч",
    waterproof: "IP68",
    color: "Чёрный",
    availability: "В наличии",
    rating: "4.7"
  },
  {
    id: 16,
    name: "Poco F7 Pro",
    brand: "Xiaomi",
    price: 44990,
    year: "2025",
    screen_size: "6.67″",
    ram: "12 ГБ",
    storage: "256 ГБ",
    screen_type: "AMOLED",
    refresh_rate: "120 Гц",
    camera_mp: "До 48 МП",
    battery: "5000–6000 мАч",
    waterproof: "IP68",
    color: "Чёрный",
    availability: "В наличии",
    rating: "4.4"
  },
  {
    id: 17,
    name: "OnePlus 13",
    brand: "Oppo",
    price: 79990,
    year: "2025",
    screen_size: "6.82″",
    ram: "16 ГБ",
    storage: "512 ГБ",
    screen_type: "AMOLED",
    refresh_rate: "120 Гц",
    camera_mp: "50–64 МП",
    battery: "6000+ мАч",
    waterproof: "IP68",
    color: "Синий",
    availability: "В наличии",
    rating: "4.7"
  },
  {
    id: 18,
    name: "Honor Magic 7 Pro",
    brand: "Huawei",
    price: 84990,
    year: "2025",
    screen_size: "6.8″",
    ram: "12 ГБ",
    storage: "512 ГБ",
    screen_type: "OLED",
    refresh_rate: "120 Гц",
    camera_mp: "200 МП+",
    battery: "5000–6000 мАч",
    waterproof: "IP68",
    color: "Фиолетовый",
    availability: "Под заказ",
    rating: "4.6"
  },
  {
    id: 19,
    name: "Motorola Edge 50 Ultra",
    brand: "Другие",
    price: 59990,
    year: "2024",
    screen_size: "6.7″",
    ram: "12 ГБ",
    storage: "512 ГБ",
    screen_type: "OLED",
    refresh_rate: "144+ Гц",
    camera_mp: "50–64 МП",
    battery: "4500–5000 мАч",
    waterproof: "IP68",
    color: "Белый",
    availability: "В наличии",
    rating: "4.5"
  },
  {
    id: 20,
    name: "Samsung Galaxy Z Fold 6",
    brand: "Samsung",
    price: 179990,
    year: "2024",
    screen_size: "7.6″",
    ram: "12 ГБ",
    storage: "512 ГБ",
    screen_type: "AMOLED",
    refresh_rate: "120 Гц",
    camera_mp: "50–64 МП",
    battery: "4500–5000 мАч",
    waterproof: "IP48",
    color: "Чёрный",
    availability: "Под заказ",
    rating: "4.6"
  },
  {
    id: 21,
    name: "iPhone 14 Pro",
    brand: "Apple",
    price: 89990,
    year: "2022 и старше",
    screen_size: "6.1″",
    ram: "6 ГБ",
    storage: "256 ГБ",
    screen_type: "OLED",
    refresh_rate: "120 Гц",
    camera_mp: "48 МП",
    battery: "До 4500 мАч",
    waterproof: "IP68",
    color: "Фиолетовый",
    availability: "В наличии",
    rating: "4.7"
  },
  {
    id: 22,
    name: "Xiaomi 13T",
    brand: "Xiaomi",
    price: 44990,
    year: "2023",
    screen_size: "6.67″",
    ram: "8 ГБ",
    storage: "256 ГБ",
    screen_type: "AMOLED",
    refresh_rate: "144+ Гц",
    camera_mp: "50–64 МП",
    battery: "5000–6000 мАч",
    waterproof: "IP68",
    color: "Зелёный",
    availability: "В наличии",
    rating: "4.4"
  },
  {
    id: 23,
    name: "Google Pixel 8 Pro",
    brand: "Google",
    price: 94990,
    year: "2023",
    screen_size: "6.7″",
    ram: "12 ГБ",
    storage: "256 ГБ",
    screen_type: "OLED",
    refresh_rate: "120 Гц",
    camera_mp: "50–64 МП",
    battery: "До 4500 мАч",
    waterproof: "IP68",
    color: "Белый",
    availability: "Под заказ",
    rating: "4.8"
  },
  {
    id: 24,
    name: "Realme 13 Pro+",
    brand: "Realme",
    price: 32990,
    year: "2025",
    screen_size: "6.7″",
    ram: "8 ГБ",
    storage: "256 ГБ",
    screen_type: "AMOLED",
    refresh_rate: "120 Гц",
    camera_mp: "До 48 МП",
    battery: "5000–6000 мАч",
    waterproof: "IP65",
    color: "Синий",
    availability: "В наличии",
    rating: "4.3"
  },
  {
    id: 25,
    name: "Samsung Galaxy S23",
    brand: "Samsung",
    price: 64990,
    year: "2023",
    screen_size: "6.1″",
    ram: "8 ГБ",
    storage: "256 ГБ",
    screen_type: "AMOLED",
    refresh_rate: "120 Гц",
    camera_mp: "50–64 МП",
    battery: "До 4500 мАч",
    waterproof: "IP68",
    color: "Чёрный",
    availability: "В наличии",
    rating: "4.6"
  },
  {
    id: 26,
    name: "Nothing Phone (2a)",
    brand: "Другие",
    price: 29990,
    year: "2024",
    screen_size: "6.7″",
    ram: "8 ГБ",
    storage: "128 ГБ",
    screen_type: "AMOLED",
    refresh_rate: "120 Гц",
    camera_mp: "До 48 МП",
    battery: "5000–6000 мАч",
    waterproof: "IP54",
    color: "Белый",
    availability: "В наличии",
    rating: "4.4"
  },
  {
    id: 27,
    name: "Asus ROG Phone 9",
    brand: "Другие",
    price: 119990,
    year: "2025",
    screen_size: "6.78″",
    ram: "16 ГБ",
    storage: "512 ГБ",
    screen_type: "AMOLED",
    refresh_rate: "144+ Гц",
    camera_mp: "50–64 МП",
    battery: "6000+ мАч",
    waterproof: "IP68",
    color: "Чёрный",
    availability: "Под заказ",
    rating: "4.7"
  },
  {
    id: 28,
    name: "iPhone 16e",
    brand: "Apple",
    price: 79990,
    year: "2025",
    screen_size: "6.1″",
    ram: "8 ГБ",
    storage: "128 ГБ",
    screen_type: "OLED",
    refresh_rate: "60 Гц",
    camera_mp: "48 МП",
    battery: "До 4500 мАч",
    waterproof: "IP68",
    color: "Чёрный",
    availability: "В наличии",
    rating: "4.5"
  },
  {
    id: 29,
    name: "Tecno Camon 30 Premier",
    brand: "Другие",
    price: 39990,
    year: "2024",
    screen_size: "6.78″",
    ram: "12 ГБ",
    storage: "512 ГБ",
    screen_type: "AMOLED",
    refresh_rate: "120 Гц",
    camera_mp: "50–64 МП",
    battery: "5000–6000 мАч",
    waterproof: "IP54",
    color: "Зелёный",
    availability: "В наличии",
    rating: "4.3"
  },
  {
    id: 30,
    name: "Samsung Galaxy Z Flip 6",
    brand: "Samsung",
    price: 109990,
    year: "2024",
    screen_size: "6.7″",
    ram: "12 ГБ",
    storage: "512 ГБ",
    screen_type: "AMOLED",
    refresh_rate: "120 Гц",
    camera_mp: "50–64 МП",
    battery: "До 4500 мАч",
    waterproof: "IP48",
    color: "Фиолетовый",
    availability: "В наличии",
    rating: "4.6"
  }
];